services:
  mariadb:
    image: 'mariadb:lts-ubi9'
    container_name: maria_db
    restart: unless-stopped
    environment:
      - 'MARIADB_DATABASE=ar_db'
      - 'MARIADB_PASSWORD=mariapassword'
      - 'MARIADB_ROOT_PASSWORD=rootpassword'
      - 'MARIADB_USER=maria'
    ports:
      - '3306:3306'
    volumes:
      - 'mariadb_data:/var/lib/mysql'

  adminer:
    image: adminer:latest
    container_name: adminer_panel
    environment:
      - ADMINER_DEFAULT_SERVER=mariadb
    ports:
      - "8081:8080" # Map host 8081 to Adminer's 8080
    restart: unless-stopped

  rabbitmq:
    image: 'rabbitmq:4.0-management'
    container_name: rabbit_mq
    restart: unless-stopped
    environment:
      - 'RABBITMQ_DEFAULT_USER=guest'
      - 'RABBITMQ_DEFAULT_PASS=guest'
#      - 'RABBITMQ_DEFAULT_VHOST=myvhost'
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - 'rabbitmq_data:/var/lib/rabbitmq'

  redis:
    image: 'redis:8.4-alpine'
    container_name: redis_cache
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/data'

volumes:
  mariadb_data:
  rabbitmq_data:
  redis_data: