package org.lucas.arbackend.dto.course;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Builder;

import java.io.Serial;
import java.io.Serializable;
import java.util.List;

@Builder
@Schema(name = "CourseResponse", description = "The structural endpoint response object detailing fully parsed multi-tenant course curriculum graphs")
public record CourseResponse(
 @Schema(description = "Unique internal entity identifier generated by database primary sequencing mechanisms", example = "2")
        Long id,

        @Schema(description = "The explicit title string of the course", example = "Cloud Architecture Foundations")
        String name,

        @Schema(description = "High level summary detail text block", example = "A starter guide to high-scale cloud design.")
        String shortDescription,

        @Schema(description = "Target demographic descriptions", example = "Junior Developers and DevOps aspirants.")
        String intendedAudience,

        @Schema(description = "Necessary core dependencies or knowledge baselines", example = "Basic understanding of networking and Linux.")
        String requirements,

        @Schema(description = "Current lifecyle publishing state classification", example = "DRAFT")
        String status,

        @Schema(description = "The aggregate calculation value summarizing all lesson section modules durations in minutes", example = "65")
        Integer totalTimeInMinutes,

        @Schema(description = "SEO-friendly, URL URL-safe alphanumeric string name permutation used for frontend browser path parameters routing cleanly", example = "cloud-architecture-foundations")
        String slug,

        @Schema(description = "Summary list detailing technical learning outcomes target goals", example = "1. Understand VPCs 2. Deploy Load Balancers 3. Manage IAM roles.")
        String learningObjectives,

        @Schema(description = "The registered administrative or owner user email address address", example = "editor@staff.com")
        String staffEmail,

        @Schema(description = "The targeted categorization tier rating", example = "BEGINNER")
        String difficulty,

        @Schema(description = "The direct asset location rendering course artwork components on customer user dashboards", example = "https://example.com/images/cloud-course.png")
        String imageUrl,

        @Schema(description = "The combined categorizations string index values matching system query tags", example = "cloud, aws, devops")
        String tags,

        @Schema(description = "The internal nested structure listing organized module nodes and localized chapter assessment entities maps")
        List<CourseChapterResponse> chapters
) implements Serializable {

    @Serial
    private static final long serialVersionUID = 1L;


}
