-- partners
CREATE TABLE partner (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  org VARCHAR(255),
  status ENUM('ACTIVE','SUSPENDED','DELETED') DEFAULT 'ACTIVE',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  end_date TIMESTAMP NULL
) ENGINE=InnoDB;

-- api keys
CREATE TABLE api_key (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  api_key_value CHAR(32) NOT NULL UNIQUE,
  secret CHAR(64) NOT NULL,
  partner_id BIGINT UNSIGNED NOT NULL,
  scopes VARCHAR(255) NOT NULL,
  status ENUM('ACTIVE','REVOKED','EXPIRED') DEFAULT 'ACTIVE',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMP NULL,
  FOREIGN KEY (partner_id) REFERENCES partner(id)
) ENGINE=InnoDB;

-- courses
CREATE TABLE course (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  partner_id BIGINT UNSIGNED NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  status ENUM('DRAFT','PUBLISHED','ARCHIVED') DEFAULT 'DRAFT',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  end_date TIMESTAMP NULL,
  FOREIGN KEY (partner_id) REFERENCES partner(id)
) ENGINE=InnoDB;

-- modules
CREATE TABLE module (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  course_id BIGINT UNSIGNED NOT NULL,
  title VARCHAR(255) NOT NULL,
  `order` INT UNSIGNED NOT NULL,
  description TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  end_date TIMESTAMP NULL,
  FOREIGN KEY (course_id) REFERENCES course(id)
) ENGINE=InnoDB;

-- assets
CREATE TABLE asset (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  module_id BIGINT UNSIGNED NOT NULL,
  type ENUM('MODEL','IMAGE','VIDEO','AUDIO','DOC') NOT NULL,
  url VARCHAR(512) NOT NULL,
  metadata_json JSON,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  end_date TIMESTAMP NULL,
  FOREIGN KEY (module_id) REFERENCES module(id)
) ENGINE=InnoDB;

-- users
CREATE TABLE user (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  first_name VARCHAR(100),
  last_name VARCHAR(100),
  role ENUM('ADMIN','TEACHER','STUDENT') DEFAULT 'STUDENT',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  end_date TIMESTAMP NULL
) ENGINE=InnoDB;

-- enrollments
CREATE TABLE enrollment (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  course_id BIGINT UNSIGNED NOT NULL,
  progress DECIMAL(5,2) DEFAULT 0.00,
  completed_at TIMESTAMP NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES user(id),
  FOREIGN KEY (course_id) REFERENCES course(id)
) ENGINE=InnoDB;